### ISSUE TITLE
SDK para Swift

### ISSUE THREAD

**Issue by ronflima** [stone-pagamentos/sdk-ios-v2#2]
O Framework não foi empacotado com o setting _define modules_, o que torna impossível a integração _seamless_ com aplicações escritas em Swift. 

Para resolver este problema, basta alterar o setting "defines module" na seção _packaging_ dos _build settings_. Trata-se de um problema trivial, mas que se não resolvido me obrigará a criar uma biblioteca wrapper desnecessária por conta de um ajuste de compilação.

**Comment by jaisonv** [comment]
Muito obrigado por levantar essa questão. Nós realmente não tínhamos pensado nisso. Eu tentei fazer a modificação conforme indicado mas não foi suficiente. Vou adicionar ao nosso backlog e em breve adicionaremos isso.

Por enquanto não é possivel usar nosso framework com um Objective-C bridging header?

**Comment by ronflima** [comment]
Obrigado pela pronta resposta.

Não. O meu cenário é bem diferente. O bridging header funciona para apps. Infelizmente o bridging header não é suportado para frameworks. Estou escrevendo um framework em Swift 2 que integra a biblioteca da Stone com o web service do meu cliente. 

A dica do "defines module" está incompleta. É preciso ainda definir o nome do módulo, o que cria um arquivo de mapeamento dentro do framework. 

A solução que encontrei foi bem torta: criei o arquivo de mapeamento na mão e o introduzi manualmente no bundle do framework da Stone. Este arquivo de mapeamento é usado pelo runtime para mapear os entry points do shared object do framework. Infelizmente, trata-se de uma solução ruim pois estou infringindo a manufatura do framework da Stone.
