### ISSUE TITLE
STNValidationProvider.validateTablesDownloaded não funciona

### ISSUE THREAD

**Issue by ronflima** [stone-pagamentos/sdk-ios-v2#3]
Este método retorna NO mesmo após completado um download de ponta a ponta sem problemas.

Se após realizado o download datas tabelas o método voltar a ser chamado o mesmo continua retornando NO, indicando que não houve download, o que está incorreto.

**Comment by jaisonv** [comment]
Vou fechar esse aqui relacionando ao #4, já que acabei respondendo por lá.
