### ISSUE TITLE
STNTableLoaderProvider.loadTables trava - 100% de uso de CPU

### ISSUE THREAD

**Issue by ronflima** [stone-pagamentos/sdk-ios-v2#4]
O cenário é o que segue:

1. Execute uma verificação de download das tabelas com STNValidationProvider.validateTablesDownloaded.
2. Se o retorno for NO, realize o download das tabelas com STNTableDownloaderProvider.downloadTables
3. Realize a carga das tabelas no device através do método STNTableLoaderProvider.loadTables
4. Repita os passos de 1 a 3. 

Resultado: O método STNTableLoaderProvider.loadTables entra em loop e não retorna, levando a CPU a 100% de consumo, drenando vertiginosamente a bateria do device.

É importante indicar que todos os métodos retornam sucesso antes de ocorrer o travamento. Tudo é feito com o Stone Code ativado e com a comunicação ao pin pad estabelecida.

**Comment by jaisonv** [comment]
Aqui nós usamos isso e não temos esse problema. Pode mandar o trecho do código em que você faz isso?

**Comment by ronflima** [comment]
Aqui está. A condition variable é necessária para forçar o sequenciamento das chamadas que descobri ocorrerem em threads separadas. Este trecho já está em uma thread diferente da main thread devido à arquitetura da solução. 

Quando este trecho é executado pela segunda vez, a validação das tabelas falha e novo download é executado. Em seguida a carga das tabelas entra em loop infinito e o consumo da CPU vai a 100%. 
```swift
        if !STNValidationProvider.validateTablesDownloaded() {
            // Download data tables
            downloaderProvider.downLoadTables { (success, error) in
                gotError = !success
                condition.signal()
            }
            condition.wait()
            if gotError {
                callback?(results: ["error" : "Failed to download tables"])
                condition.unlock()
                return
            }
            if STNValidationProvider.validatePinpadConnection() {
                self.loaderProvider.loadTables { (success, error) in
                    gotError = !success
                }
                if gotError {
                    callback?(results: ["error" : "Failed to load tables into the device"])
                    condition.unlock()
                    return
                }
            }
        }
```

**Comment by ronflima** [comment]
Esta é a pilha da thread que provoca o travamento.

#0	0x00000001000d3634 in -[STNEADSessionController readByte] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:59
#1	0x00000001000d396c in -[STNEADSessionController readMessage] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:108
#2	0x00000001000dde48 in -[STNCommands sendCommandTLI] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Commands/STNCommands.m:405
#3	0x00000001000db098 in -[STNTableLoader loadXML:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Tables/STNTableLoader.m:73
#4	0x00000001000d91d8 in -[STNTableLoaderProvider loadTables:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Providers/STNTableLoaderProvider.m:19
#5	0x00000001000b3e98 in StoneGateway.initialize((results : [String : AnyObject]?) -> ()?) -> () at /Users/ronaldo/Documents/Projetos/Pagpop/sdk-ios/PagpopSDK/Gateway/StoneGateway.swift:67
#6	0x00000001000b5420 in protocol witness for Gateway.initialize((results : [String : AnyObject]?) -> ()?) -> () in conformance StoneGateway at /Users/ronaldo/Documents/Projetos/Pagpop/sdk-ios/PagpopSDK/Gateway/StoneGateway.swift:31
#7	0x00000001000c1d68 in GatewayManager.initialize((results : [String : AnyObject]?) -> ()?) -> () at /Users/ronaldo/Documents/Projetos/Pagpop/sdk-ios/PagpopSDK/Gateway/GatewayManager.swift:34
#8	0x00000001000bb7e8 in GatewayInitializationStep.main() -> () at /Users/ronaldo/Documents/Projetos/Pagpop/sdk-ios/PagpopSDK/Workflow/Steps/GatewayInitializationStep.swift:15

**Comment by jaisonv** [comment]
@ronflima Eu encontrei um bug na checagem da tabela e fiz uma correção. Pode testar com essa build [StoneSDK.framework.zip](https://github.com/stone-pagamentos/sdk-ios-v2/files/273467/StoneSDK.framework.zip)?

**Comment by ronflima** [comment]
Obrigado, Jaison. Vou introduzir esta build no meu code base e assim que terminar de testar te aviso nos próximos 40 minutos.

**Comment by ronflima** [comment]
Testado. O efeito agora é este:

1. STNValidationProvider.validateTablesDownloaded sempre retorna YES, mesmo quando o app sofre um fresh install.
2. Continuo observando o loop e o excesso de consumo de CPU, conforme observado anteriormente.

Aqui está o stack tracing:

```
#0	0x00000001000a7414 in -[STNEADSessionController readByte] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:61
#1	0x00000001000a775c in -[STNEADSessionController readMessage] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:108
#2	0x00000001000b1c38 in -[STNCommands sendCommandTLI] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Commands/STNCommands.m:405
#3	0x00000001000aee88 in -[STNTableLoader loadXML:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Tables/STNTableLoader.m:73
#4	0x00000001000acfc8 in -[STNTableLoaderProvider loadTables:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Providers/STNTableLoaderProvider.m:19
#5	0x00000001000858bc in StoneGateway.initialize((results : [String : AnyObject]?) -> ()?) -> () at StoneGateway.swift:87
#6	0x0000000100086d8c in protocol witness for Gateway.initialize((results : [String : AnyObject]?) -> ()?) -> () in conformance StoneGateway at StoneGateway.swift:31
#7	0x0000000100094e38 in GatewayManager.initialize((results : [String : AnyObject]?) -> ()?) -> () at GatewayManager.swift:34
#8	0x000000010008e378 in GatewayInitializationStep.main() -> () at GatewayInitializationStep.swift:15
```

No console, observei esta mensagem que aparentemente está truncada:

```
2016-05-19 21:07:08.555 SDKDemo[2010:607001] Reachability Flag Status: -R ------- networkStatusForFlags
2016-05-19 21:07:08.894 SDKDemo[2010:607001] +++++++++ TLI012002014053065
```

SDKDemo é o nome da minha aplicação de testes.

Bom, o que pude perceber em termos de comportamento é que a verificação das tabelas continua não funcionando, ou seja, ao invés de retornar sempre NO, agora retorna sempre YES. Eu abri um outro defeito para averiguar este fato.

**Comment by jaisonv** [comment]
@ronflima Ah sim. É que quando você ativa o stone code ele já faz o download das tabelas. Se fizer um teste antes de ativar vai ver que ele retorna falso. Eu tinha feito isso para abstrair essa camada. Agora fiquei em dúvida se é realmente necessario esse provider. E ainda o load das tabelas para o Pinpad também vai ocorrer automaticamente durante uma transação se o Pinpad estiver desatualizado

E outra coisa que notei é que vc usa o gotError para pegar o valor do sucess quando você poderia testar o erro de dentro do bloco.

Seria algo assim:

```swift
if !STNValidationProvider.validateTablesDownloaded() {
            // Download data tables
            downloaderProvider.downLoadTables { (success, error) in
                 if !success {
                     callback?(results: ["error" : "Failed to download tables"])
                 }
            }
            if STNValidationProvider.validatePinpadConnection() {
                 self.loaderProvider.loadTables { (success, error) in
                     if !success {
                         callback?(results: ["error" : "Failed to load tables into the device"])
                     }
                }
            }
        }
```

Ve se isso resolve por aqui.

E faz um teste por favor. Como na ativação, ele já executa o download das tabelas, testa se nesse momento ele entra em loop ou causa alto consumo de CPU.

**Comment by ronflima** [comment]
Existe um bom motivo pelo qual eu trato o erro FORA dos blocos. O bloco executado por downloadTables é executado em outra thread enquanto o bloco executado por loadTables é síncrono. No meu design, há uma condition variable para que cada uma das coisas ocorra sincronamente. O callback não pode ser chamado em uma thread qualquer. Ele é executado dentro da thread da função não qual está toda a lógica de inicialização do seu bloco.

Agora, se o seu design foi feito para realizar o download das tabelas assincronamente enquanto a carga das mesmas no pinpad ocorre na thread corrente, pode ser que esteja aí o problema do travamento. Ou seja, estou usando suas rotinas de forma incorreta. Vou alterar meu código para trabalhar assincronamente como a sua sugestão e te retorno.

**Comment by ronflima** [comment]
Novamente, 100% de CPU e thread suspensa. Porém, o stack trace indica outro ponto, agora durante a escrita no display do device.

```
#0	0x000000010017f3cc in -[STNEADSessionController readByte] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:61
#1	0x000000010017f74c in -[STNEADSessionController readMessage] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:108
#2	0x00000001001887c4 in -[STNCommands sendCommandDSP:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Commands/STNCommands.m:56
#3	0x000000010017d100 in -[STNDisplayProvider displayMessage:withBlock:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Providers/STNDisplayProvider.m:21
#4	0x000000010015dfc8 in StoneGateway.display(String) -> () at StoneGateway.swift:113
#5	0x000000010015f218 in StoneGateway.(initialize((results : [String : AnyObject]?) -> ()?) -> ()).($defer #1)() -> () at StoneGateway.swift:41
#6	0x000000010015d6d0 in StoneGateway.initialize((results : [String : AnyObject]?) -> ()?) -> () at StoneGateway.swift:35
#7	0x000000010015eb70 in protocol witness for Gateway.initialize((results : [String : AnyObject]?) -> ()?) -> () in conformance StoneGateway at StoneGateway.swift:31
#8	0x000000010016cc88 in GatewayManager.initialize((results : [String : AnyObject]?) -> ()?) -> () at GatewayManager.swift:34
#9	0x00000001001661c8 in GatewayInitializationStep.main() -> () at GatewayInitializationStep.swift:15
```

O stack trace é bastante revelador. O problema ocorrem no método readByte da classe STNEADSessionController. Os outros stack traces que coloquei aqui também apontam para este método.

**Comment by ronflima** [comment]
Alterei meu código para chamar a carga das tabelas antes da inicialização do Stone Code. O stack trace é este:

```
#0	0x0000000100147404 in -[STNEADSessionController readByte] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:61
#1	0x000000010014774c in -[STNEADSessionController readMessage] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/EADSession/STNEADSessionController.m:108
#2	0x00000001001507c4 in -[STNCommands sendCommandDSP:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Commands/STNCommands.m:56
#3	0x0000000100145100 in -[STNDisplayProvider displayMessage:withBlock:] at /Users/jaisonv/Documents/Projetos/stone-sdk-2.0/Providers/STNDisplayProvider.m:21
#4	0x0000000100125fc8 in StoneGateway.display(String) -> () at StoneGateway.swift:113
#5	0x0000000100127218 in StoneGateway.(initialize((results : [String : AnyObject]?) -> ()?) -> ()).($defer #1)() -> () at StoneGateway.swift:41
#6	0x00000001001256d0 in StoneGateway.initialize((results : [String : AnyObject]?) -> ()?) -> () at StoneGateway.swift:35
#7	0x0000000100126b70 in protocol witness for Gateway.initialize((results : [String : AnyObject]?) -> ()?) -> () in conformance StoneGateway at StoneGateway.swift:31
#8	0x0000000100134c88 in GatewayManager.initialize((results : [String : AnyObject]?) -> ()?) -> () at GatewayManager.swift:34
#9	0x000000010012e1c8 in GatewayInitializationStep.main() -> () at GatewayInitializationStep.swift:15


Observe que o travamento ocorre exatamente no mesmo método.

**Comment by jaisonv** [comment]
Se o seu callback faz alguma chamada na main thread você pode chamar dentro do bloco com o seguinte método (eu só tenho agora o exemplo em Objective-C):
```objc
dispatch_async(dispatch_get_main_queue(),
                               ^{
                                   // executa main thread
                               });
```

E sobre chamar a carga antes da inicialização, eu quis dizer que a ativação do Stone code roda um método que faz o download das tabelas para o dispositivo. Sugeri que tente rodar o "STNValidationProvider.validateTablesDownloaded()" antes de ativar o Stone code para comprovar que alí, onde as tabelas ainda não foram baixadas, o retorno será falso.

**Comment by ronflima** [comment]
Pois bem. 

Eu executei o método validateTablesDownloaded conforme você havia especificado. Sim, ele retornou falso antes da ativação do stone code, conforme você havia dito. Talvez seja uma boa ideia descrever isso na documentação para evitar dores-de-cabeça.

Sobre os meus callbacks, bem, o meu design é bem mais complexo e há uma série de premissas que não vem ao caso para a análise deste problema. Toda a rotina de inicialização do gateway stone foi desenhada para ser síncrona com relação a si mesma e por isso há alguns pontos de sincronismo conforme eu havia comentado. 

De toda forma, o método ```[STNEADSessionController readByte]``` aparece nos stack traces como sendo o responsável por mandar a CPU a 100% e provocar um hang up no processo. O fato é que todas as rotinas do seu SDK são chamadas dentro do método _main_ de um NSOperation, ou seja, tudo é disparado de uma thread à parte. Tenho preferência pelas Operation Queues pois as dispatch queues foram projetadas para dar suporte a programas escritos em C. Ambas as formas usam o GCD para disparar threads e estão atreladas aos run-loops, sendo totalmente equivalentes.

Apesar do travamento ocorrer inicialmente com as cargas da tabela, também verifiquei o mesmo efeito na escrita de uma string no display, conforme reportei acima em outro stack trace, o que me leva a crer que há um problema relacionado com concorrência no código do seu session controller.

Bom, não estamos avançando na pesquisa deste problema. E não vamos avançar enquanto você supor que o problema está no meu código. Os stack traces são determinísticos e demonstram claramente que há um loop infinito no método do seu session controller. Além disso, o Xcode demonstra claramente que a thread que vai a 100% de utilização de CPU é justamente a thread na qual o código do SDK Stone está executando.

Da minha parte, quero ajudar a solucionar este problema. Tanto é verdade que estou fornecendo o que posso de informações pertinentes na análise deste problema.

**Comment by jaisonv** [comment]
No momento em que ocorre a ativação, a CPU chega a 100%?

**Comment by ronflima** [comment]
Não. Quando ocorre a ativação, tudo processa-se como deveria.

**Comment by jaisonv** [comment]
Pelo que notei, analisando seu relato, o problema só ocorre quando há uma comunicação com o Pinpad. Conforme conversei com o Leandro da Pagpop, gostaria de ter um projeto demo simulando as chamadas da forma que vocês estão executando, assim poderei analisar melhor e fazer um debug. Fico no aguardo desse projeto para tentar chegar a uma solução.
