### ISSUE TITLE
Testes em SandBox

### ISSUE THREAD

**Issue by gusmelki** [stone-pagamentos/sdk-ios-v2#5]
Percebi que não tem um ambiente para testes do envio das transações.

Se não me engano para Android vocês tem um método para isto.

**Comment by jaisonv** [comment]
Olá, Gustavo. A SDK iOS ainda não possui essa possibilidade. Pretendemos adicionar em uma próxima versão.

**Comment by jaisonv** [comment]
Olá @gusmelki. Fizemos uma atualização no SDK. E agora contemplamos um ambiente de homologação como no Android.

Para que os endpoints de homologação funcionem, basta adicionar a key "Stone Homologation" no "Info.plist" com o tipo "Boolean" e marcar "YES". Não esqueça de mudar para "**NO**" quando for subir para produção.

A versão nova encontra-se [aqui](https://github.com/stone-pagamentos/sdk-ios-v2/releases/tag/v2.1.0). Mais detalhes podem ser encontrado no README.
